//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReggieScholar
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public string username { get; set; }
        public string Project_ID { get; set; }
        public string Project_Name { get; set; }
        public string Course_ID { get; set; }
        public string Keyword1 { get; set; }
        public string Keyword2 { get; set; }
        public string Keyword3 { get; set; }
        public string Abstract { get; set; }
        public string Live_Link { get; set; }
        public string Video_Link { get; set; }
        public string Chair_Name { get; set; }
        public string Chair_Email { get; set; }
        public string Comm_Name { get; set; }
        public string Comm_Email { get; set; }
        public string Gadvisor_Name { get; set; }
        public string Gadvisor_Email { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Reject_Reason { get; set; }
        public Nullable<int> Num_Views { get; set; }
        public Nullable<int> Num_Dloads { get; set; }
        public string Pic_File { get; set; }
        public string Proj_Pdf_File { get; set; }
        public string Proj_Zip_File { get; set; }
        public string Pres_Date { get; set; }
        public Nullable<int> Dislike_Count { get; set; }
        public Nullable<int> Like_Count { get; set; }
        public string Approval_Status1 { get; set; }
        public string Approval_Status2 { get; set; }
        public string Approval_Status3 { get; set; }
        public string Reviewer_Comment1 { get; set; }
        public string Reviewer_Comment2 { get; set; }
        public string Reviewer_Comment3 { get; set; }
    }
}
