//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReggieScholar
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string username { get; set; }
        public string userpassword { get; set; }
        public string User_Type { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public string Approve_Status { get; set; }
    }
}
