//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReggieScholar
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string username { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Security_Question { get; set; }
        public string Security_Answer { get; set; }
        public string Acct_Reason { get; set; }
        public string Semester_Completion { get; set; }
        public Nullable<System.DateTime> Account_Date { get; set; }
        public Nullable<int> Progress_Bar { get; set; }
        public string Comment_Box { get; set; }
        public string Comment_Status { get; set; }
        public string Reviewer_Comments { get; set; }
        public string College_Dept { get; set; }
    }
}
